# Generated by Django 5.1.1 on 2024-11-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('network_admin', 'Network Admin'), ('noc_user', 'NOC User'), ('system_admin', 'System Admin'), ('network_engineer', 'Network Engineer'), ('can_view', 'Can View'), ('can_checkout_items', 'Can Checkout Items')], default='noc_user', max_length=50),
        ),
    ]
