# Generated by Django 5.1.1 on 2025-01-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FibreInfrastructures',
        ),
    ]
