# Generated by Django 5.1.1 on 2025-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibreInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Start Location')),
                ('intermediary_locations', models.TextField(blank=True, help_text='Comma-separated list of intermediary locations.', null=True, verbose_name='Intermediary Locations')),
                ('destination_location', models.CharField(max_length=255, verbose_name='Destination Location')),
                ('location_code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Fibre Location Code')),
            ],
            options={
                'verbose_name': 'Fibre Infrastructure',
                'verbose_name_plural': 'Fibre Infrastructures',
                'ordering': ['location_code'],
            },
        ),
    ]
