# Generated by Django 5.1.1 on 2024-11-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0002_assets_going_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='verifier_user_approve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
