# Generated by Django 5.1.1 on 2024-11-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('can_view', 'Can View'), ('can_checkout_items', 'Can Checkout Items')], default='can_view', max_length=50),
        ),
    ]
