# Generated by Django 5.1.1 on 2024-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0002_alter_checkout_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart_items',
            field=models.ManyToManyField(related_name='checkouts', to='KENETAssets.cart'),
        ),
    ]
