# Generated by Django 5.1.1 on 2024-11-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0002_delete_assetmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date when the movement was recorded')),
                ('comments', models.TextField(blank=True, help_text='Additional details about the movement', null=True)),
                ('assets', models.ForeignKey(help_text='Asset being moved', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='KENETAssets.assets')),
                ('person_moving', models.ForeignKey(blank=True, help_text='Person responsible for moving the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Movement',
                'verbose_name_plural': 'Asset Movements',
                'ordering': ['-date_created'],
            },
        ),
    ]
