# Generated by Django 5.1.1 on 2024-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/users/'),
        ),
    ]
