# Generated by Django 5.1.1 on 2024-11-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0003_assetsmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name_alias',
            field=models.CharField(default='nsame', max_length=100),
            preserve_default=False,
        ),
    ]
