# Generated by Django 5.1.1 on 2024-11-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0004_checkout_user_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout_url_link',
            field=models.URLField(blank=True, help_text='Optional URL for checkout link', null=True),
        ),
    ]
