# Generated by Django 5.1.1 on 2024-10-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0004_orderitem_quantity_checkout_delete_dispatchcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
