# Generated by Django 5.1.1 on 2024-11-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0005_alter_assets_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'asset', 'added_at')},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
