# Generated by Django 5.1.1 on 2024-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0006_alter_checkout_verifier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='sent_to_erp',
            field=models.BooleanField(default=False),
        ),
    ]
