# Generated by Django 5.1.1 on 2024-11-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0006_alter_cart_unique_together_delete_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'asset')},
        ),
    ]
