# Generated by Django 5.1.1 on 2024-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0007_assets_sent_to_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsmovement',
            name='sent_to_erp',
            field=models.BooleanField(default=False),
        ),
    ]
