# Generated by Django 5.1.1 on 2024-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0008_releaseadminformdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='authorizing_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='quantity_issued',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='checkout',
            name='quantity_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='checkout',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
