# Generated by Django 5.1.1 on 2024-11-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0009_alter_assets_going_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='going_location',
            new_name='destination_location',
        ),
    ]
