# Generated by Django 5.1.1 on 2024-11-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0009_checkout_authorizing_name_checkout_quantity_issued_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseAdminFormData',
        ),
        migrations.DeleteModel(
            name='ReleaseFormData',
        ),
    ]
