# Generated by Django 5.1.1 on 2024-11-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0011_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='project',
            field=models.CharField(blank=True, choices=[('noc', 'NOC'), ('netdev', 'NetDev'), ('bolt', 'BOLT'), ('dci', 'DCI'), ('data_centre_infrastructure', 'Data Centre Infrastructure')], default='noc', max_length=100, null=True),
        ),
    ]
