# Generated by Django 5.1.1 on 2024-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0012_remove_delivery_status_alter_delivery_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name_alias',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
