# Generated by Django 5.1.1 on 2024-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0013_alter_location_name_alter_location_name_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
