# Generated by Django 5.1.1 on 2024-12-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0015_alter_assets_options_alter_checkout_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpdf',
            name='user',
        ),
    ]
