# Generated by Django 5.1.1 on 2025-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KENETAssets', '0017_checkout_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
