# Generated by Django 5.1.1 on 2024-10-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.CharField(blank=True, choices=[('instore', 'In Store'), ('tested', 'Tested'), ('default', 'Default'), ('onsite', 'On Site'), ('pending_release', 'Pending Release')], default='instore', max_length=20, null=True),
        ),
    ]
