# Generated by Django 5.1.1 on 2024-10-18 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0003_alter_cart_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='person_receiving',
            field=models.ForeignKey(blank=True, help_text='User who received the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
