# Generated by Django 5.1.1 on 2024-10-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0003_assets_new_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='new_location',
            field=models.CharField(blank=True, default='University of Nairobi KENET STORE', max_length=200, null=True),
        ),
    ]
