# Generated by Django 5.1.1 on 2024-10-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0005_alter_delivery_invoice_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
