# Generated by Django 5.1.1 on 2024-10-11 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0006_location_alter_assets_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('date_delivered', models.DateField(default=django.utils.timezone.now)),
                ('person_receiving', models.CharField(max_length=255)),
                ('invoice_file', models.FileField(upload_to='invoices/')),
                ('invoice_number', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
