# Generated by Django 5.1.1 on 2024-10-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0007_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date_delivered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
