# Generated by Django 5.1.1 on 2024-10-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='new_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
