# Generated by Django 5.1.1 on 2024-10-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0009_alter_cart_options_rename_date_added_cart_added_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('current_location', models.CharField(max_length=255)),
                ('new_location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity_required', models.PositiveIntegerField()),
                ('quantity_issued', models.PositiveIntegerField()),
                ('serial_number', models.CharField(max_length=100)),
                ('kenet_tag', models.CharField(max_length=100)),
                ('authorizing_name', models.CharField(max_length=255)),
                ('authorization_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
