# Generated by Django 5.1.1 on 2024-10-31 06:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0011_alter_assets_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_description_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='delivery',
            field=models.ForeignKey(blank=True, help_text='Associated delivery for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='qyfy.delivery'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the movement')),
                ('comments', models.TextField(blank=True, help_text='Additional details about the movement', null=True)),
                ('assets', models.ManyToManyField(help_text='Assets being moved', related_name='movements', to='qyfy.assets')),
                ('destination_location', models.ForeignKey(blank=True, help_text='Location to where the asset is being moved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_destination', to='qyfy.location')),
                ('person_moving', models.ForeignKey(blank=True, help_text='Person responsible for moving the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(blank=True, help_text='Location from where the asset is being moved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_source', to='qyfy.location')),
            ],
            options={
                'verbose_name': 'Asset Movement',
                'verbose_name_plural': 'Asset Movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateTimeField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked_out', 'Checked Out'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='qyfy.cart')),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_suppliers', to='qyfy.suppliers'),
        ),
    ]
