# Generated by Django 5.1.1 on 2024-10-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyfy', '0013_remove_assets_new_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='new_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
