# Generated by Django 5.1.1 on 2024-12-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/'),
        ),
    ]
